name: MineZ Legendary Weapons
main: com.cin316.minezweapons.MineZWeapons
version: 1.0
description: Adds MineZ's Legendary Weapons to the vanilla game.
commands:
  minezweapons:
    description: Gives info on MineZ Legendary Weapons!
    usage: /minezweapons <help|give|list> [weapon]
    permission: minezweapons.info
    permission-message: You don't have permissions to use minezweapons.info.
permissions:
  minezweapons.info:
    description: Allows you to check MineZ Weapon's info (name, version, etc.).
    default: true
  minezweapons.use:
    description: Allows you to use MineZ Weapon's Custom Weapons.
    default: true